/*
  # Seed Govern sidebar groups and pages

  Creates 6 sidebar groups with ~35 child topic pages for the
  Govern section. Organized by governance function: constitution,
  RFC process, working groups, shared segments, federal compliance,
  and Foundation governance.
*/

DO $$
DECLARE
  v_section_id uuid;
  v_group_id uuid;
BEGIN
  SELECT id INTO v_section_id FROM nav_sections WHERE slug = 'govern';

  -- Group 1: The Constitution
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'The Constitution', 'the-constitution', 1)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Article I — Founding purpose', 'article-i-founding-purpose', 1, 'The founding purpose of the CivikStack ecosystem.', '<h2 id="article-i">Article I — Founding purpose</h2><p>Article I establishes the founding purpose of the CivikStack ecosystem: to provide open, non-capturable infrastructure for measuring whether civic services actually work when residents try to use them. This article cannot be amended — it is the permanent foundation on which all other governance is built.</p>'),
  (v_group_id, 'Article II — The architectural covenant', 'article-ii-the-architectural-covenant', 2, 'The immutable architectural commitments.', '<h2 id="article-ii">Article II — The architectural covenant</h2><p>Article II establishes the architectural commitments that cannot be changed: the RoutePack seven-container architecture, the Privacy Envelope, the step-level telemetry requirement, and the DFR measurement methodology. These are the structural foundations that make the ecosystem trustworthy.</p>'),
  (v_group_id, 'Article III — The vertical contract', 'article-iii-the-vertical-contract', 3, 'The requirements every vertical must satisfy.', '<h2 id="article-iii">Article III — The vertical contract</h2><p>Article III defines the four requirements that every vertical application must satisfy: versioned pathway artifacts, step-level telemetry, Privacy Envelope compliance, and lifecycle governance participation. The vertical contract is what ensures that every application in the ecosystem generates the data needed for access reliability measurement.</p>'),
  (v_group_id, 'Article IV — The shared segment commons', 'article-iv-the-shared-segment-commons', 4, 'Governance of community-owned pathway components.', '<h2 id="article-iv">Article IV — The shared segment commons</h2><p>Article IV establishes the shared segment commons as community-governed property. Shared segments cannot be privatized, cannot be removed without community process, and must be maintained by the working group responsible for their domain. This article protects the community knowledge embedded in shared pathway components.</p>'),
  (v_group_id, 'Article V — The adoption-to-reliability pipeline', 'article-v-the-adoption-to-reliability-pipeline', 5, 'The governance of ecosystem growth and quality.', '<h2 id="article-v">Article V — The adoption-to-reliability pipeline</h2><p>Article V establishes the governance process for bringing new verticals, new counties, and new shared segments into the ecosystem. It defines the adoption pipeline stages, the certification requirements, and the quality gates that protect the ecosystem''s integrity as it grows.</p>'),
  (v_group_id, 'Article VI — Community participation and governance rights', 'article-vi-community-participation-and-governance-rights', 6, 'Who can participate in governance and how.', '<h2 id="article-vi">Article VI — Community participation and governance rights</h2><p>Article VI establishes the governance rights of ecosystem participants: counties, agencies, frontline workers, community advocates, developers, and researchers. It defines who can propose RFCs, who can vote in working groups, and who can participate in constitutional amendment processes.</p>'),
  (v_group_id, 'Article VII — The non-capture covenant', 'article-vii-the-non-capture-covenant', 7, 'The irrevocable commitment against ecosystem capture.', '<h2 id="article-vii">Article VII — The non-capture covenant</h2><p>Article VII establishes the irrevocable non-capture covenant: no entity — not the Foundation, not a vendor, not a government agency, not a funder — can acquire control over the CivikStack ecosystem. This article is unamendable. It is the structural guarantee that protects every participant''s investment in the ecosystem.</p>'),
  (v_group_id, 'Article VIII — Amendment', 'article-viii-amendment', 8, 'How the constitution can and cannot be changed.', '<h2 id="article-viii">Article VIII — Amendment</h2><p>Article VIII defines the amendment process for the constitution. Articles I (founding purpose), II (architectural covenant), and VII (non-capture covenant) are unamendable. Other articles can be amended through a supermajority RFC process with extended comment periods and community-wide ratification.</p>');

  -- Group 2: The RFC Process
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'The RFC Process', 'the-rfc-process', 2)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'What requires an RFC', 'what-requires-an-rfc', 1, 'Which changes require the formal RFC process.', '<h2 id="what-requires-rfc">What requires an RFC</h2><p>An RFC is required for: any change to the RoutePack schema, any new shared segment, any change to an existing shared segment, any change to the vertical contract, any change to the governance process itself, and any change to the federation protocol. Bug fixes, documentation updates, and vertical-specific changes that do not affect the shared infrastructure do not require an RFC.</p>'),
  (v_group_id, 'Proposing a shared segment', 'proposing-a-shared-segment', 2, 'How to propose a new shared segment through the RFC process.', '<h2 id="propose-segment">Proposing a shared segment</h2><p>To propose a new shared segment, submit an RFC that includes: the segment definition, the use cases across multiple verticals, the proposed schema, the governance working group that would maintain it, and the migration plan for verticals that would adopt it. The RFC follows the standard comment period and rough consensus process.</p>'),
  (v_group_id, 'Proposing a schema change', 'proposing-a-schema-change', 3, 'How to propose changes to the RoutePack schema.', '<h2 id="propose-schema">Proposing a schema change</h2><p>Schema change RFCs require additional rigor: a backward compatibility analysis, a migration plan for all deployed counties, an impact assessment for all verticals, and a proposed migration window. Schema changes that break backward compatibility require an extended comment period and supermajority approval.</p>'),
  (v_group_id, 'Proposing a governance invariant change', 'proposing-a-governance-invariant-change', 4, 'How to propose changes to governance rules.', '<h2 id="propose-governance">Proposing a governance invariant change</h2><p>Governance invariant changes — modifications to the RFC process itself, changes to working group structure, or amendments to amendable constitutional articles — require the highest level of community engagement: extended comment periods, community-wide notification, and supermajority ratification.</p>'),
  (v_group_id, 'The comment period', 'the-comment-period', 5, 'How the RFC comment period works.', '<h2 id="comment-period">The comment period</h2><p>Every RFC has a comment period during which any ecosystem participant can submit comments, objections, or amendments. Standard RFCs have a 30-day comment period. Schema changes and governance changes have a 60-day comment period. Constitutional amendments have a 90-day comment period.</p>'),
  (v_group_id, 'Rough consensus — how it is determined', 'rough-consensus-how-it-is-determined', 6, 'How rough consensus is evaluated for RFC decisions.', '<h2 id="rough-consensus">Rough consensus — how it is determined</h2><p>CivikStack uses the IETF rough consensus model: the decision is based on the technical merits of the arguments, not on a vote count. The working group chair evaluates whether the substantive objections have been addressed, not whether everyone agrees. Detailed dissents are recorded even when the consensus moves forward.</p>'),
  (v_group_id, 'Foundation publication process', 'foundation-publication-process', 7, 'How approved RFCs become published standards.', '<h2 id="publication">Foundation publication process</h2><p>After an RFC achieves rough consensus, the Foundation publishes it as a standard. Publication includes: updating the affected schema or governance document, notifying all county deployments, publishing migration guidance, and opening the migration window for counties to adopt the change.</p>'),
  (v_group_id, 'Migration window management', 'migration-window-management', 8, 'How migration windows work for RFC-driven changes.', '<h2 id="migration-window">Migration window management</h2><p>Migration windows give counties time to adopt published changes. Standard changes have a 90-day migration window. Breaking changes have a 180-day migration window. The Foundation provides migration tooling, testing environments, and support during the migration window.</p>'),
  (v_group_id, 'Active RFCs', 'active-rfcs', 9, 'Currently open RFCs in the comment period.', '<h2 id="active-rfcs">Active RFCs</h2><p>This page lists all currently active RFCs — proposals that are in the comment period and open for community input. Each listing includes the RFC title, proposer, comment period dates, current status, and links to the full proposal and comment thread.</p>'),
  (v_group_id, 'RFC archive', 'rfc-archive', 10, 'Historical record of all completed RFCs.', '<h2 id="rfc-archive">RFC archive</h2><p>The RFC archive contains the complete historical record of every RFC submitted to the CivikStack governance process — accepted, rejected, and withdrawn. Each archived RFC includes the full proposal, all comments, the rough consensus determination, and any dissents recorded.</p>');

  -- Group 3: Working Groups
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Working Groups', 'working-groups', 3)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'How working groups are organized', 'how-working-groups-are-organized', 1, 'Structure and function of CivikStack working groups.', '<h2 id="wg-organized">How working groups are organized</h2><p>Working groups are organized by domain: each of the ten verticals has a working group, plus the Shared Segment Commons working group and the Schema and Infrastructure working group. Each working group has a chair, a charter, regular meetings, and decision-making authority within its domain.</p>'),
  (v_group_id, 'Current working groups', 'current-working-groups', 2, 'List of all active working groups.', '<h2 id="current-wgs">Current working groups</h2><p>CivikStack currently has twelve active working groups: Housing, Early Childhood, Benefits, Workforce, Reentry, Behavioral Health, Healthcare Coverage, Student Support, Whole-Person Care, Civil Legal Aid, Shared Segment Commons, and Schema and Infrastructure. Each working group meets regularly and maintains its own communication channels.</p>'),
  (v_group_id, 'Joining a working group', 'joining-a-working-group', 3, 'How to become a working group participant.', '<h2 id="join-wg">Joining a working group</h2><p>Working group participation is open to anyone in the CivikStack ecosystem: county staff, agency workers, developers, community advocates, researchers, and Foundation members. To join, contact the working group chair or attend a regular meeting. There are no prerequisites — domain knowledge and willingness to participate are sufficient.</p>');

  -- Group 4: The Shared Segment Commons
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'The Shared Segment Commons', 'the-shared-segment-commons', 4)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'What shared segments exist', 'what-shared-segments-exist', 1, 'Catalog of all published shared segments.', '<h2 id="existing-segments">What shared segments exist</h2><p>This page catalogs all published shared segments in the CivikStack commons. Each listing includes the segment name, version, maintaining working group, verticals that use it, and a brief description of its function. Shared segments cover cross-cutting functions like eligibility verification, consent management, document collection, and referral processing.</p>'),
  (v_group_id, 'How to use a shared segment', 'how-to-use-a-shared-segment', 2, 'How to incorporate a shared segment into your vertical.', '<h2 id="use-segment">How to use a shared segment</h2><p>To incorporate a shared segment into your vertical, reference it by version in your pathway artifact. The shared segment''s steps, telemetry events, and failure codes become part of your pathway. The segment version is locked at pathway publication time — upgrading to a new segment version requires a new pathway version.</p>'),
  (v_group_id, 'How to propose a new shared segment', 'how-to-propose-a-new-shared-segment', 3, 'RFC process for proposing new shared segments.', '<h2 id="propose-new-segment">How to propose a new shared segment</h2><p>Proposing a new shared segment requires an RFC that demonstrates the segment''s utility across multiple verticals. The RFC must include the segment schema, proposed governance working group, adoption plan, and evidence that the segment captures genuine cross-cutting functionality rather than domain-specific behavior.</p>'),
  (v_group_id, 'How to propose a correction to an existing segment', 'how-to-propose-a-correction-to-an-existing-segment', 4, 'How to fix problems in published shared segments.', '<h2 id="correct-segment">How to propose a correction to an existing segment</h2><p>Shared segment corrections follow a streamlined RFC process. If the correction is backward-compatible, it requires a 14-day comment period and working group approval. If the correction changes the segment''s schema or semantics, it follows the full schema change RFC process.</p>'),
  (v_group_id, 'Segment version history', 'segment-version-history', 5, 'Version history for all shared segments.', '<h2 id="segment-history">Segment version history</h2><p>This page provides the complete version history for every shared segment in the commons. Each version entry includes the version number, publication date, change summary, RFC reference (if applicable), and the migration guidance for counties upgrading from the previous version.</p>');

  -- Group 5: Federal Compliance Alignment
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Federal Compliance Alignment', 'federal-compliance-alignment', 5)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'How CivikStack outputs are validated', 'how-civikstack-outputs-are-validated', 1, 'The validation process for compliance outputs.', '<h2 id="output-validation">How CivikStack outputs are validated</h2><p>CivikStack compliance outputs are validated against the specific data requirements of each federal funding stream. The validation process includes: schema conformance testing, data completeness verification, cross-referencing with source telemetry, and comparison with historical reporting to identify anomalies.</p>'),
  (v_group_id, 'HUD — CoC and HMIS alignment', 'hud-coc-and-hmis-alignment', 2, 'Mapping CivikStack housing data to HUD requirements.', '<h2 id="hud-alignment">HUD — CoC and HMIS alignment</h2><p>This section documents how CivikStack Housing vertical telemetry maps to HUD Continuum of Care and HMIS data requirements. Each required HMIS data element is mapped to a specific telemetry event field, with validation rules and transformation logic documented.</p>'),
  (v_group_id, 'CMS — Medicaid managed care alignment', 'cms-medicaid-managed-care-alignment', 3, 'Mapping CivikStack data to CMS requirements.', '<h2 id="cms-alignment">CMS — Medicaid managed care alignment</h2><p>This section documents how CivikStack Healthcare Coverage vertical telemetry maps to CMS managed care reporting requirements. Each required data element is mapped to specific telemetry events with validation and transformation logic.</p>'),
  (v_group_id, 'DOL — WIOA title I alignment', 'dol-wioa-title-i-alignment', 4, 'Mapping CivikStack workforce data to WIOA requirements.', '<h2 id="dol-alignment">DOL — WIOA title I alignment</h2><p>This section documents how CivikStack Workforce vertical telemetry maps to WIOA Title I reporting requirements including participant demographics, service delivery events, credential attainment, and employment outcomes.</p>'),
  (v_group_id, 'DOJ — Second Chance Act alignment', 'doj-second-chance-act-alignment', 5, 'Mapping CivikStack reentry data to DOJ requirements.', '<h2 id="doj-alignment">DOJ — Second Chance Act alignment</h2><p>This section documents how CivikStack Reentry vertical telemetry maps to Second Chance Act reporting requirements including service delivery, recidivism reduction measures, and community reintegration outcomes.</p>'),
  (v_group_id, 'SAMHSA — 988 alignment', 'samhsa-988-alignment', 6, 'Mapping CivikStack behavioral health data to SAMHSA requirements.', '<h2 id="samhsa-alignment">SAMHSA — 988 alignment</h2><p>This section documents how CivikStack Behavioral Health vertical telemetry maps to SAMHSA 988 crisis line reporting requirements including call response times, follow-up engagement, and crisis resolution outcomes.</p>'),
  (v_group_id, 'LSC — Performance reporting alignment', 'lsc-performance-reporting-alignment', 7, 'Mapping CivikStack legal aid data to LSC requirements.', '<h2 id="lsc-alignment">LSC — Performance reporting alignment</h2><p>This section documents how CivikStack Civil Legal Aid vertical telemetry maps to Legal Services Corporation performance reporting requirements including case types, service hours, outcomes, and client access measures.</p>'),
  (v_group_id, 'HHS — McKinney-Vento and IDEA alignment', 'hhs-mckinney-vento-and-idea-alignment', 8, 'Mapping CivikStack student support data to HHS requirements.', '<h2 id="hhs-alignment">HHS — McKinney-Vento and IDEA alignment</h2><p>This section documents how CivikStack Student Support vertical telemetry maps to McKinney-Vento and IDEA reporting requirements including student identification, service connection, educational stability, and accommodation delivery.</p>'),
  (v_group_id, 'Requesting a compliance certification review', 'requesting-a-compliance-certification-review', 9, 'How to request formal certification of compliance alignment.', '<h2 id="certification-review">Requesting a compliance certification review</h2><p>Counties can request a formal compliance certification review from the Foundation. The review validates that the county''s CivikStack deployment generates compliance outputs that meet the specific requirements of their federal funding streams. Certification provides documented assurance for program officers and auditors.</p>'),
  (v_group_id, 'The program officer engagement process', 'the-program-officer-engagement-process', 10, 'How to engage federal program officers with CivikStack compliance outputs.', '<h2 id="program-officer">The program officer engagement process</h2><p>This section provides guidance for introducing CivikStack compliance outputs to federal and state program officers. It includes talking points, data samples, comparison frameworks, and the Foundation''s contact information for program officers who want to evaluate CivikStack reporting.</p>');

  -- Group 6: Foundation Governance
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Foundation Governance', 'foundation-governance', 6)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Foundation structure and bylaws summary', 'foundation-structure-and-bylaws-summary', 1, 'Summary of the Foundation organizational structure.', '<h2 id="foundation-structure">Foundation structure and bylaws summary</h2><p>The CivikStack Foundation is organized as a nonprofit entity with a board of directors, an executive director, and a technical steering committee. The bylaws establish the governance structure, decision-making processes, and accountability mechanisms. This section provides a summary — the full bylaws are available on request.</p>'),
  (v_group_id, 'The irrevocable non-assertion covenant', 'the-irrevocable-non-assertion-covenant', 2, 'The legal commitment preventing IP-based capture.', '<h2 id="non-assertion">The irrevocable non-assertion covenant</h2><p>The non-assertion covenant is a legally binding commitment that no intellectual property claims will be asserted against any user, contributor, or deployer of CivikStack. The covenant is irrevocable — it cannot be withdrawn by the Foundation, its successors, or any future entity that might acquire the Foundation''s assets.</p>'),
  (v_group_id, 'IP policy', 'ip-policy', 3, 'Intellectual property policy for the ecosystem.', '<h2 id="ip-policy">IP policy</h2><p>The CivikStack IP policy requires that all contributions be made under the project''s open source license and that contributors certify they have the right to make the contribution. The policy is designed to prevent any entity from introducing encumbered IP into the ecosystem.</p>'),
  (v_group_id, 'The open source license', 'the-open-source-license', 4, 'The license governing CivikStack code.', '<h2 id="open-source-license">The open source license</h2><p>CivikStack is released under an open source license that permits use, modification, and distribution by anyone for any purpose. The specific license choice balances permissive use with protections against proprietary capture, ensuring that improvements to the core infrastructure remain available to the ecosystem.</p>'),
  (v_group_id, 'Financial transparency', 'financial-transparency', 5, 'The Foundation commitment to financial openness.', '<h2 id="financial-transparency">Financial transparency</h2><p>The Foundation publishes annual financial reports, donor disclosures, and budget allocations. Financial transparency is a governance requirement, not a courtesy — the ecosystem participants who depend on the Foundation have the right to understand how Foundation resources are used.</p>'),
  (v_group_id, 'Contacting the Foundation', 'contacting-the-foundation', 6, 'How to reach the CivikStack Foundation.', '<h2 id="contact">Contacting the Foundation</h2><p>The Foundation can be reached through its public communication channels for general inquiries, through the security disclosure process for vulnerability reports, through the program officer engagement process for compliance questions, and through the working group chairs for domain-specific governance questions.</p>');

END $$;
