/*
  # Seed Build sidebar groups and pages

  Creates 7 sidebar groups with ~52 child topic pages for the
  Build section. Technical reference organized by developer task
  sequence: architecture, schemas, building, deploying, observability,
  design governance, and contributing.
*/

DO $$
DECLARE
  v_section_id uuid;
  v_group_id uuid;
BEGIN
  SELECT id INTO v_section_id FROM nav_sections WHERE slug = 'build';

  -- Group 1: Architecture
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Architecture', 'architecture', 1)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'System overview', 'system-overview', 1, 'High-level architecture of the CivikStack system.', '<h2 id="system-overview">System overview</h2><p>CivikStack is a four-layer architecture: the RoutePack data layer (seven containers), the CivikGrid infrastructure layer (Kafka, Kubernetes, Unity Catalog), the vertical application layer (ten domain-specific applications), and the federation layer (cross-county coordination). Each layer has a defined contract with the layers above and below it.</p>'),
  (v_group_id, 'The four layers', 'the-four-layers', 2, 'Detailed description of each architectural layer.', '<h2 id="four-layers">The four layers</h2><p>The four layers of CivikStack separate concerns cleanly: RoutePack defines the data model, CivikGrid provides the infrastructure, vertical applications implement domain-specific service delivery, and the federation layer enables cross-county coordination. Each layer can evolve independently as long as it maintains its contract with adjacent layers.</p>'),
  (v_group_id, 'RoutePack core — seven containers', 'routepack-core-seven-containers', 3, 'Technical specification of the RoutePack container architecture.', '<h2 id="routepack-core">RoutePack core — seven containers</h2><p>The seven RoutePack containers — Pathway, Telemetry, DFR, Lifecycle, Privacy Envelope, Failure Code, and Shared Segment — define the complete data model for pathway measurement. This section provides the technical specification for each container including schema definitions, validation rules, and inter-container relationships.</p>'),
  (v_group_id, 'CivikGrid infrastructure stack', 'civikgrid-infrastructure-stack', 4, 'Technical specification of the CivikGrid infrastructure.', '<h2 id="civikgrid-stack">CivikGrid infrastructure stack</h2><p>The CivikGrid infrastructure stack includes Kafka for telemetry streaming, Kubernetes for container orchestration, Unity Catalog for data governance, PostgreSQL for persistent storage, and the federation sync service for cross-county coordination. This section documents the infrastructure dependencies and configuration for each scale tier.</p>'),
  (v_group_id, 'Unity Catalog data architecture', 'unity-catalog-data-architecture', 5, 'How Unity Catalog organizes and governs CivikStack data.', '<h2 id="unity-catalog-arch">Unity Catalog data architecture</h2><p>Unity Catalog provides the data governance layer that organizes CivikStack data into catalogs, schemas, and tables with fine-grained access control. This section documents the catalog structure, schema organization, access policies, and the Privacy Envelope enforcement implementation.</p>'),
  (v_group_id, 'Kafka topic architecture', 'kafka-topic-architecture', 6, 'How Kafka topics are organized for telemetry streaming.', '<h2 id="kafka-topics">Kafka topic architecture</h2><p>The Kafka topic architecture defines how telemetry events flow from vertical applications through the DFR computation engine to the compliance reporting pipeline. Topics are organized by vertical, by event type, and by privacy classification. This section documents the topic naming convention, partitioning strategy, and retention policies.</p>'),
  (v_group_id, 'Kubernetes namespace architecture', 'kubernetes-namespace-architecture', 7, 'How Kubernetes namespaces isolate CivikStack components.', '<h2 id="k8s-namespaces">Kubernetes namespace architecture</h2><p>The Kubernetes namespace architecture isolates vertical applications from each other and from infrastructure services. Network policies enforce the architectural boundaries. This section documents the namespace naming convention, network policy templates, resource quotas, and service mesh configuration.</p>'),
  (v_group_id, 'Network topology and enforcement', 'network-topology-and-enforcement', 8, 'Network architecture and security boundaries.', '<h2 id="network-topology">Network topology and enforcement</h2><p>Network topology defines which components can communicate with which other components. Network policies enforce these boundaries at the infrastructure layer. This section documents the network topology for each scale tier, the network policy templates, and the verification procedures for confirming correct enforcement.</p>'),
  (v_group_id, 'The federation model', 'the-federation-model', 9, 'Technical specification of cross-county federation.', '<h2 id="federation-model">The federation model</h2><p>The federation model enables independent county CivikGrid deployments to share anonymized access reliability data, synchronized shared segment versions, and coordinated schema updates. This section documents the federation protocol, the Delta Sharing integration, and the Foundation sync service architecture.</p>');

  -- Group 2: Schemas and APIs
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Schemas and APIs', 'schemas-and-apis', 2)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Telemetry event schema', 'telemetry-event-schema', 1, 'Complete schema for telemetry events.', '<h2 id="telemetry-schema">Telemetry event schema</h2><p>The telemetry event schema defines the structure of every step-level observation in CivikStack. Each event includes the pathway version reference, step identifier, timestamp, outcome classification, failure code (if applicable), and the metadata fields required for DFR computation — all within the Privacy Envelope constraint.</p>'),
  (v_group_id, 'Pathway artifact schema', 'pathway-artifact-schema', 2, 'Complete schema for pathway versioned artifacts.', '<h2 id="pathway-schema">Pathway artifact schema</h2><p>The pathway artifact schema defines the structure of a versioned service pathway. It includes step definitions, sequence rules, expected duration ranges, success and failure conditions, and the relationships between steps. The schema supports branching pathways, optional steps, and parallel step execution.</p>'),
  (v_group_id, 'Lifecycle state schema', 'lifecycle-state-schema', 3, 'Schema for lifecycle state transitions.', '<h2 id="lifecycle-schema">Lifecycle state schema</h2><p>The lifecycle state schema defines the valid states a pathway can occupy and the transitions between them. Each state transition is recorded as an immutable event with the actor, timestamp, reason, and any associated governance decision reference.</p>'),
  (v_group_id, 'Failure code taxonomy', 'failure-code-taxonomy', 4, 'Complete taxonomy of standardized failure codes.', '<h2 id="failure-taxonomy">Failure code taxonomy</h2><p>The failure code taxonomy provides a standardized classification system for step failures across all verticals. Codes are organized hierarchically: system-level codes (infrastructure failures), process-level codes (workflow failures), resource-level codes (capacity failures), and client-level codes (access barriers). Each vertical extends the base taxonomy with domain-specific codes.</p>'),
  (v_group_id, 'Cross-vertical referral event schema', 'cross-vertical-referral-event-schema', 5, 'Schema for cross-vertical referral events.', '<h2 id="referral-schema">Cross-vertical referral event schema</h2><p>The cross-vertical referral event schema defines the structure of referral events that span multiple verticals. It includes the originating vertical, destination vertical, referral reason, expected timeline, and outcome tracking fields. The schema maintains the Privacy Envelope across vertical boundaries.</p>'),
  (v_group_id, 'Inter-service API contracts', 'inter-service-api-contracts', 6, 'API contracts between CivikStack services.', '<h2 id="api-contracts">Inter-service API contracts</h2><p>Inter-service API contracts define the interfaces between CivikStack components: the telemetry ingestion API, the DFR computation API, the lifecycle management API, the compliance reporting API, and the federation sync API. Each contract includes request/response schemas, authentication requirements, rate limits, and error handling specifications.</p>'),
  (v_group_id, 'Delta Sharing protocol', 'delta-sharing-protocol', 7, 'Delta Sharing integration for cross-county data sharing.', '<h2 id="delta-sharing">Delta Sharing protocol</h2><p>The Delta Sharing protocol enables cross-county sharing of anonymized access reliability data through the federation layer. This section documents the Delta Sharing server configuration, share definitions, recipient management, and the data anonymization pipeline that ensures compliance with the Privacy Envelope across county boundaries.</p>'),
  (v_group_id, 'Foundation sync protocol', 'foundation-sync-protocol', 8, 'Protocol for synchronizing with the Foundation ecosystem.', '<h2 id="foundation-sync">Foundation sync protocol</h2><p>The Foundation sync protocol manages the bidirectional synchronization between county CivikGrid deployments and the Foundation ecosystem. It handles shared segment version synchronization, schema version updates, conformance certification status, and anonymized access reliability data contribution to the ecosystem commons.</p>');

  -- Group 3: Building a Vertical Application
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Building a Vertical Application', 'building-a-vertical-application', 3)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'The vertical contract — four requirements', 'the-vertical-contract-four-requirements', 1, 'The four requirements every vertical must satisfy.', '<h2 id="vertical-contract">The vertical contract — four requirements</h2><p>Every vertical application in CivikStack must satisfy four requirements: treat service pathways as versioned artifacts, generate step-level telemetry that conforms to the telemetry event schema, maintain the Privacy Envelope, and participate in lifecycle governance. These four requirements are the vertical contract — they define what it means to be a CivikStack vertical.</p>'),
  (v_group_id, 'Wayfinder artifacts required', 'wayfinder-artifacts-required', 2, 'Design artifacts required before building.', '<h2 id="wayfinder-artifacts">Wayfinder artifacts required</h2><p>Before building a vertical application, you must produce the Wayfinder design artifacts: the Architects foundation document (domain analysis and architectural decisions), the Canvas surface architecture (UI and interaction design), the Operations playbook (deployment and maintenance procedures), and the Intelligence model (measurement and reporting design).</p>'),
  (v_group_id, 'The vertical application template', 'the-vertical-application-template', 3, 'Starter template for building a new vertical.', '<h2 id="vertical-template">The vertical application template</h2><p>The vertical application template provides a working starting point for building a new vertical. It includes the namespace configuration, telemetry integration, pathway serving, Publish Gate integration, and a sample pathway with working telemetry. Clone the template and customize it for your domain.</p>'),
  (v_group_id, 'Namespace and network policy configuration', 'namespace-and-network-policy-configuration', 4, 'Kubernetes namespace setup for your vertical.', '<h2 id="namespace-config">Namespace and network policy configuration</h2><p>Each vertical runs in its own Kubernetes namespace with network policies that enforce architectural boundaries. This section provides the namespace configuration templates, network policy definitions, and the verification procedures for confirming correct isolation.</p>'),
  (v_group_id, 'Telemetry integration pattern', 'telemetry-integration-pattern', 5, 'How to integrate telemetry generation into your vertical.', '<h2 id="telemetry-integration">Telemetry integration pattern</h2><p>The telemetry integration pattern defines how your vertical generates step-level telemetry events and publishes them to the Kafka telemetry pipeline. This section includes the client library usage, event construction, Privacy Envelope enforcement, and error handling for telemetry delivery failures.</p>'),
  (v_group_id, 'Pathway serving integration', 'pathway-serving-integration', 6, 'How your vertical serves pathway artifacts.', '<h2 id="pathway-serving">Pathway serving integration</h2><p>Pathway serving integration defines how your vertical retrieves the current published pathway version and presents it to users. This includes the pathway cache, version resolution, step rendering, and the mechanism for detecting when a new pathway version has been published.</p>'),
  (v_group_id, 'Publish Gate integration', 'publish-gate-integration', 7, 'How to integrate with the Publish Gate conformance system.', '<h2 id="publish-gate">Publish Gate integration</h2><p>The Publish Gate validates that every pathway published through your vertical conforms to the RoutePack schema, generates correct telemetry, maintains the Privacy Envelope, and meets the vertical contract requirements. This section documents how to integrate your vertical with the Publish Gate and how to interpret validation results.</p>'),
  (v_group_id, 'Compliance reporting integration', 'compliance-reporting-integration', 8, 'How to implement compliance reporting in your vertical.', '<h2 id="compliance-integration">Compliance reporting integration</h2><p>Each vertical must implement compliance reporting that maps its telemetry to the specific data elements required by its federal funding streams. This section documents the compliance reporting framework, the mapping templates for each funding stream, and the report generation pipeline.</p>'),
  (v_group_id, 'The conformance test suite', 'the-conformance-test-suite', 9, 'Testing your vertical against the CivikStack contract.', '<h2 id="conformance-tests">The conformance test suite</h2><p>The conformance test suite validates that your vertical satisfies the four requirements of the vertical contract. It includes telemetry validation tests, Privacy Envelope enforcement tests, lifecycle governance tests, and compliance reporting tests. Your vertical must pass the full conformance suite before certification.</p>'),
  (v_group_id, 'Vertical certification process', 'vertical-certification-process', 10, 'How to certify your vertical for production use.', '<h2 id="certification">Vertical certification process</h2><p>Vertical certification is the process of validating that a vertical application satisfies the vertical contract and is ready for production deployment. Certification requires passing the conformance test suite, completing the Wayfinder design review, and receiving working group approval for verticals that use shared segments.</p>');

  -- Group 4: Deployment and Operations
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Deployment and Operations', 'deployment-and-operations', 4)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Helm chart reference', 'helm-chart-reference', 1, 'Complete reference for CivikStack Helm charts.', '<h2 id="helm-charts">Helm chart reference</h2><p>The CivikStack Helm charts provide templated Kubernetes manifests for deploying every component of the CivikGrid infrastructure and vertical applications. This reference documents every chart, its values, its dependencies, and its configuration options.</p>'),
  (v_group_id, 'Values file by tier', 'values-file-by-tier', 2, 'Helm values files for each scale tier.', '<h2 id="values-by-tier">Values file by tier</h2><p>Each scale tier has a pre-configured values file that sets appropriate resource limits, replica counts, storage sizes, and feature flags. This section provides the reference values file for each tier with detailed explanations of every configuration parameter.</p>'),
  (v_group_id, 'Configuration parameters', 'configuration-parameters', 3, 'Complete list of all configuration parameters.', '<h2 id="config-params">Configuration parameters</h2><p>This reference documents every configuration parameter in the CivikStack system, organized by component. Each parameter includes its name, type, default value, allowed values, and the effect of changing it.</p>'),
  (v_group_id, 'Certificate management', 'certificate-management', 4, 'TLS certificate management for CivikGrid.', '<h2 id="cert-management">Certificate management</h2><p>CivikGrid uses TLS certificates for inter-service communication, federation connections, and external access. This section documents the certificate requirements, the cert-manager integration, certificate rotation procedures, and troubleshooting guides for certificate-related issues.</p>'),
  (v_group_id, 'Secrets management', 'secrets-management', 5, 'Managing secrets and sensitive configuration.', '<h2 id="secrets">Secrets management</h2><p>CivikGrid integrates with Kubernetes secrets and optionally with external secret management systems for managing sensitive configuration including database credentials, API keys, federation tokens, and encryption keys. This section documents the secrets architecture and operational procedures.</p>'),
  (v_group_id, 'Schema version management', 'schema-version-management', 6, 'Managing RoutePack schema versions across deployments.', '<h2 id="schema-versions">Schema version management</h2><p>RoutePack schema versions are managed through the Foundation sync protocol. When a new schema version is published, county deployments must plan and execute a migration. This section documents the schema version lifecycle, migration planning, backward compatibility guarantees, and the migration window management process.</p>'),
  (v_group_id, 'Shared segment version management', 'shared-segment-version-management', 7, 'Managing shared segment versions.', '<h2 id="segment-versions">Shared segment version management</h2><p>Shared segments are versioned independently of the RoutePack schema. When a new shared segment version is published by the working group, counties can adopt it on their own timeline. This section documents the segment version lifecycle, adoption procedures, and conflict resolution.</p>');

  -- Group 5: Observability and Maintenance
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Observability and Maintenance', 'observability-and-maintenance', 5)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Prometheus metrics reference', 'prometheus-metrics-reference', 1, 'All CivikStack Prometheus metrics.', '<h2 id="prometheus-metrics">Prometheus metrics reference</h2><p>CivikStack exposes Prometheus metrics for every component: telemetry pipeline throughput, DFR computation latency, lifecycle state transition counts, Publish Gate validation results, and vertical application health. This reference documents every metric, its type, labels, and alerting thresholds.</p>'),
  (v_group_id, 'Grafana dashboard templates', 'grafana-dashboard-templates', 2, 'Pre-built Grafana dashboards for CivikStack monitoring.', '<h2 id="grafana-dashboards">Grafana dashboard templates</h2><p>CivikStack includes pre-built Grafana dashboards for operational monitoring: the infrastructure overview dashboard, the telemetry pipeline dashboard, the DFR computation dashboard, the vertical application dashboard, and the federation health dashboard. This section provides the dashboard templates and customization guidance.</p>'),
  (v_group_id, 'Alert threshold reference', 'alert-threshold-reference', 3, 'Recommended alerting thresholds for all metrics.', '<h2 id="alert-thresholds">Alert threshold reference</h2><p>This reference provides recommended alerting thresholds for every CivikStack metric, organized by severity: critical (immediate action required), warning (investigation required), and informational (monitoring awareness). Thresholds are calibrated for each scale tier.</p>'),
  (v_group_id, 'Runtime state authority — degraded conditions', 'runtime-state-authority-degraded-conditions', 4, 'How CivikStack handles degraded operational states.', '<h2 id="degraded-conditions">Runtime state authority — degraded conditions</h2><p>When CivikStack components enter degraded states — telemetry pipeline backpressure, DFR computation delays, federation connection failures — the runtime state authority determines the appropriate response. This section documents the degraded state taxonomy, the automated response policies, and the manual intervention procedures.</p>'),
  (v_group_id, 'DFR computation monitoring', 'dfr-computation-monitoring', 5, 'Monitoring the DFR computation pipeline.', '<h2 id="dfr-monitoring">DFR computation monitoring</h2><p>DFR computation monitoring tracks the health and accuracy of the distance-from-reality measurement engine. Key metrics include computation latency, queue depth, error rates, and statistical validation checks that confirm the DFR values are within expected ranges.</p>'),
  (v_group_id, 'Privacy Envelope monitoring', 'privacy-envelope-monitoring', 6, 'Monitoring Privacy Envelope enforcement.', '<h2 id="privacy-monitoring">Privacy Envelope monitoring</h2><p>Privacy Envelope monitoring continuously validates that no personally identifiable information is present in the telemetry pipeline, the DFR computation engine, or the compliance reporting outputs. This section documents the monitoring checks, the violation detection system, and the automated response procedures.</p>'),
  (v_group_id, 'Publish Gate monitoring', 'publish-gate-monitoring', 7, 'Monitoring the Publish Gate conformance system.', '<h2 id="publish-gate-monitoring">Publish Gate monitoring</h2><p>Publish Gate monitoring tracks the health and performance of the pathway publication conformance system. Key metrics include validation throughput, rejection rates by category, and the average time from submission to publication or rejection.</p>');

  -- Group 6: Wayfinder for Developers
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Wayfinder for Developers', 'wayfinder-for-developers', 6)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Architects artifacts — requirements and templates', 'architects-artifacts-requirements-and-templates', 1, 'Architects foundation document templates.', '<h2 id="architects-artifacts">Architects artifacts — requirements and templates</h2><p>The Architects foundation document establishes the domain analysis, audience architecture, information architecture, and architectural decisions for a CivikStack component. This section provides the template, requirements, and examples for producing the Architects artifact.</p>'),
  (v_group_id, 'Canvas artifacts — requirements and templates', 'canvas-artifacts-requirements-and-templates', 2, 'Canvas surface architecture templates.', '<h2 id="canvas-artifacts">Canvas artifacts — requirements and templates</h2><p>The Canvas surface architecture defines the visual design, interaction patterns, component hierarchy, and responsive behavior for a CivikStack component. This section provides the template, requirements, and examples for producing the Canvas artifact.</p>'),
  (v_group_id, 'Operations artifacts — requirements and templates', 'operations-artifacts-requirements-and-templates', 3, 'Operations playbook templates.', '<h2 id="operations-artifacts">Operations artifacts — requirements and templates</h2><p>The Operations playbook defines the deployment procedures, monitoring requirements, maintenance procedures, and incident response plans for a CivikStack component. This section provides the template, requirements, and examples for producing the Operations artifact.</p>'),
  (v_group_id, 'Intelligence artifacts — requirements and templates', 'intelligence-artifacts-requirements-and-templates', 4, 'Intelligence model templates.', '<h2 id="intelligence-artifacts">Intelligence artifacts — requirements and templates</h2><p>The Intelligence model defines the measurement design, reporting requirements, data pipeline architecture, and analytical capabilities for a CivikStack component. This section provides the template, requirements, and examples for producing the Intelligence artifact.</p>'),
  (v_group_id, 'The design review process', 'the-design-review-process', 5, 'How design reviews work in CivikStack development.', '<h2 id="design-review">The design review process</h2><p>Every CivikStack component must pass a Wayfinder design review before it can be certified. The review validates that the component satisfies the five Wayfinder constraints (Truth, Reliability, Fidelity, Elegance, Evolution) and that all four Wayfinder artifacts are complete and consistent.</p>'),
  (v_group_id, 'Anti-patterns in CivikStack development', 'anti-patterns-in-civikstack-development', 6, 'Common mistakes to avoid when building on CivikStack.', '<h2 id="anti-patterns">Anti-patterns in CivikStack development</h2><p>This section documents the most common anti-patterns in CivikStack development: breaking the Privacy Envelope with logging, bypassing the Publish Gate for expedience, treating DFR as a performance metric rather than a health metric, building verticals that do not participate in lifecycle governance, and designing UIs that expose raw telemetry data to frontline workers.</p>');

  -- Group 7: Contributing to the Codebase
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Contributing to the Codebase', 'contributing-to-the-codebase', 7)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Repository structure', 'repository-structure', 1, 'How the CivikStack repository is organized.', '<h2 id="repo-structure">Repository structure</h2><p>The CivikStack repository is organized into directories by architectural layer: <code>routepack/</code> for the data layer, <code>civikgrid/</code> for the infrastructure layer, <code>verticals/</code> for the vertical applications, and <code>federation/</code> for the federation services. Each directory has its own build, test, and documentation structure.</p>'),
  (v_group_id, 'Development environment setup', 'development-environment-setup', 2, 'Setting up a local development environment.', '<h2 id="dev-environment">Development environment setup</h2><p>This guide walks through setting up a local CivikStack development environment using the Tier 1 desktop deployment. It includes prerequisites, installation steps, the development workflow, and the local testing procedures.</p>'),
  (v_group_id, 'Contribution standards', 'contribution-standards', 3, 'Code quality and process standards for contributions.', '<h2 id="contribution-standards">Contribution standards</h2><p>CivikStack contributions must meet specific quality standards: code must pass the linter and formatter, tests must cover the change, the Privacy Envelope must be maintained, and the Wayfinder design constraints must be satisfied. This section documents the complete contribution standards.</p>'),
  (v_group_id, 'Pull request process', 'pull-request-process', 4, 'How to submit and review pull requests.', '<h2 id="pr-process">Pull request process</h2><p>Pull requests follow a structured review process: automated CI validation, code review by a maintainer, conformance test validation, and — for changes that affect the vertical contract or shared segments — working group review. This section documents the complete pull request lifecycle.</p>'),
  (v_group_id, 'Security disclosure policy', 'security-disclosure-policy', 5, 'How to report security vulnerabilities.', '<h2 id="security-disclosure">Security disclosure policy</h2><p>If you discover a security vulnerability in CivikStack, report it through the Foundation''s responsible disclosure process. Do not file a public issue. This section documents the disclosure process, expected response timelines, and the Foundation''s commitment to addressing security issues.</p>');

END $$;
