/*
  # Seed Community sidebar groups and pages

  Creates 7 sidebar groups with ~30 child topic pages for the
  Community section. Organized from understanding to action to
  participation: what CivikStack reveals, community services,
  using evidence, contributing, practitioners, research, and mission.
*/

DO $$
DECLARE
  v_section_id uuid;
  v_group_id uuid;
BEGIN
  SELECT id INTO v_section_id FROM nav_sections WHERE slug = 'community';

  -- Group 1: What CivikStack Reveals
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'What CivikStack Reveals', 'what-civikstack-reveals', 1)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'How to read an access reliability finding', 'how-to-read-an-access-reliability-finding', 1, 'Understanding access reliability data in plain language.', '<h2 id="read-finding">How to read an access reliability finding</h2><p>An access reliability finding tells you whether a civic service pathway is working as promised. When you see a finding that says "Housing Navigation intake pathway: DFR 3.7," it means the housing intake process has drifted significantly from its design — residents are experiencing a process that is 3.7 units away from what was intended. Higher numbers mean more drift. Zero means the pathway is working exactly as designed.</p><p>This section walks through real examples of access reliability findings, explaining what each number means and what it implies for the residents trying to use that service.</p>'),
  (v_group_id, 'Understanding DFR scores', 'understanding-dfr-scores', 2, 'What Distance From Reality scores mean for non-technical audiences.', '<h2 id="understand-dfr">Understanding DFR scores</h2><p>DFR — Distance From Reality — is the core measurement in CivikStack. Think of it as a health score for a service pathway, but inverted: lower is better. A DFR of 0 means the service works exactly as designed. A DFR of 1 means minor drift. A DFR above 3 means significant problems. This section explains DFR ranges, what drives changes in DFR, and how to interpret trends over time.</p>'),
  (v_group_id, 'What geographic access gaps mean', 'what-geographic-access-gaps-mean', 3, 'Understanding geographic patterns in access reliability.', '<h2 id="geographic-gaps">What geographic access gaps mean</h2><p>When access reliability varies by geography — when the same housing program works well in one neighborhood but poorly in another — that is a geographic access gap. CivikStack makes these gaps visible by computing DFR at the geographic level. This section explains how to read geographic access data and what it reveals about how your community''s services are distributed.</p>'),
  (v_group_id, 'What institutional accountability looks like in the data', 'what-institutional-accountability-looks-like-in-the-data', 4, 'How access reliability data reveals institutional performance.', '<h2 id="accountability">What institutional accountability looks like in the data</h2><p>Access reliability data reveals institutional accountability in concrete, measurable terms. When a benefits enrollment pathway consistently fails at the document verification step, the data shows that the institution has a systemic problem — not that individual residents are failing. This section explains how to identify institutional accountability patterns in CivikStack data.</p>'),
  (v_group_id, 'What CivikStack does not reveal', 'what-civikstack-does-not-reveal', 5, 'The limits of access reliability measurement.', '<h2 id="does-not-reveal">What CivikStack does not reveal</h2><p>CivikStack measures whether service pathways work as designed. It does not measure whether the service design itself is good, whether the funding level is adequate, or whether the service should exist in the first place. It does not measure individual worker performance. It does not replace the need for community voice, lived experience, or democratic governance. This section is honest about what CivikStack cannot do.</p>'),
  (v_group_id, 'Privacy — what the system cannot see and why', 'privacy-what-the-system-cannot-see-and-why', 6, 'How privacy is protected in the measurement architecture.', '<h2 id="privacy">Privacy — what the system cannot see and why</h2><p>CivikStack cannot see who you are. The Privacy Envelope — a structural separation built into the architecture — ensures that the telemetry used for measurement never contains personally identifiable information. The system measures the pathway, not the person. This section explains the Privacy Envelope in plain language and addresses common concerns about data privacy in civic technology.</p>');

  -- Group 2: Your Community's Services
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Your Community''s Services', 'your-communitys-services', 2)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Finding your county''s access reliability data', 'finding-your-countys-access-reliability-data', 1, 'How to find access reliability data for your area.', '<h2 id="find-data">Finding your county''s access reliability data</h2><p>If your county has deployed CivikStack, access reliability data is available through the county''s public access reliability dashboard. This section explains how to find your county''s dashboard, what data is publicly available, and what data requires a formal data access request.</p>'),
  (v_group_id, 'Reading a vertical-level access reliability report', 'reading-a-vertical-level-access-reliability-report', 2, 'How to interpret access reliability reports for specific service domains.', '<h2 id="vertical-report">Reading a vertical-level access reliability report</h2><p>Each vertical — housing, benefits, workforce, and so on — produces its own access reliability report. This section walks through a sample report, explaining each section: the overall DFR score, the step-by-step breakdown, the failure mode analysis, the geographic distribution, and the trend over time.</p>'),
  (v_group_id, 'Understanding geographic breakdowns', 'understanding-geographic-breakdowns', 3, 'How to read geographic access reliability data.', '<h2 id="geographic-breakdowns">Understanding geographic breakdowns</h2><p>Geographic breakdowns show how access reliability varies across your county. A service that works well county-wide might still fail in specific neighborhoods. This section explains how to read geographic maps, what the color coding means, and how to identify areas where your community''s services are underperforming.</p>'),
  (v_group_id, 'Comparing service access across communities', 'comparing-service-access-across-communities', 4, 'How to compare access reliability between areas.', '<h2 id="compare-communities">Comparing service access across communities</h2><p>When multiple counties or communities publish access reliability data, you can compare how the same type of service performs in different areas. This section explains how to make fair comparisons, what to account for when comparing different deployments, and how to use comparison data in advocacy.</p>');

  -- Group 3: Using the Evidence
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Using the Evidence', 'using-the-evidence', 3)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'How access reliability data supports advocacy', 'how-access-reliability-data-supports-advocacy', 1, 'Using CivikStack data in advocacy work.', '<h2 id="data-advocacy">How access reliability data supports advocacy</h2><p>Access reliability data transforms advocacy from anecdote to evidence. Instead of saying "the housing system doesn''t work," you can say "the housing intake pathway has a DFR of 4.2, meaning it has drifted significantly from its design, and the drift is concentrated in three neighborhoods." This section provides frameworks for using access reliability data in advocacy contexts.</p>'),
  (v_group_id, 'Documenting institutional accountability', 'documenting-institutional-accountability', 2, 'How to use CivikStack data to document accountability.', '<h2 id="document-accountability">Documenting institutional accountability</h2><p>When a service pathway fails systematically, the data documents institutional accountability. This section explains how to compile access reliability evidence into accountability documentation — for public hearings, for media reporting, for funder communications, and for direct engagement with service agencies.</p>'),
  (v_group_id, 'Requesting pathway correction timelines', 'requesting-pathway-correction-timelines', 3, 'How to request that identified problems be corrected.', '<h2 id="correction-timelines">Requesting pathway correction timelines</h2><p>When CivikStack data reveals a pathway problem, community members can request correction timelines from the responsible agency. This section explains the correction request process, what to expect from the agency response, and how to follow up on correction commitments using ongoing access reliability data.</p>'),
  (v_group_id, 'How to cite CivikStack findings', 'how-to-cite-civikstack-findings', 4, 'Citation standards for access reliability data.', '<h2 id="cite-findings">How to cite CivikStack findings</h2><p>When using CivikStack data in reports, presentations, media, or research, proper citation ensures the data is traceable to its source. This section provides citation formats for access reliability findings, DFR scores, and geographic access data — for academic, journalistic, and advocacy contexts.</p>'),
  (v_group_id, 'Sample advocacy frameworks', 'sample-advocacy-frameworks', 5, 'Templates and frameworks for evidence-based advocacy.', '<h2 id="advocacy-frameworks">Sample advocacy frameworks</h2><p>This section provides sample advocacy frameworks that integrate access reliability data: the service accountability brief template, the geographic equity analysis template, the pathway correction request template, and the public testimony framework. Each template is designed to be adapted to your community''s specific context.</p>');

  -- Group 4: Contributing to the Ecosystem
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Contributing to the Ecosystem', 'contributing-to-the-ecosystem', 4)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'How community observations improve pathways', 'how-community-observations-improve-pathways', 1, 'How community input feeds into pathway improvement.', '<h2 id="community-observations">How community observations improve pathways</h2><p>Community observations are a vital input to the pathway governance process. When a resident or advocate observes that a service pathway does not match reality — the steps are wrong, the timeline is unrealistic, the requirements have changed — that observation can trigger a governance review. This section explains how community observations flow into the pathway correction process.</p>'),
  (v_group_id, 'Submitting pathway failure reports through community partners', 'submitting-pathway-failure-reports-through-community-partners', 2, 'How to report pathway failures through partner organizations.', '<h2 id="failure-reports">Submitting pathway failure reports through community partners</h2><p>Community members can submit pathway failure reports through designated community partner organizations. These reports are reviewed by the relevant working group and can trigger pathway governance reviews. This section explains the submission process and identifies community partner organizations in your area.</p>'),
  (v_group_id, 'Participating in working groups', 'participating-in-working-groups', 3, 'How community members can join working groups.', '<h2 id="participate-wg">Participating in working groups</h2><p>Working groups are open to community participation. Your lived experience with civic services provides essential perspective that cannot be replaced by technical knowledge alone. This section explains how to find and join working groups relevant to your interests and how community voices are integrated into governance decisions.</p>'),
  (v_group_id, 'Contributing domain knowledge to shared segments', 'contributing-domain-knowledge-to-shared-segments', 4, 'How practitioner and community knowledge improves shared segments.', '<h2 id="domain-knowledge">Contributing domain knowledge to shared segments</h2><p>Shared segments — the reusable pathway components that work across multiple service domains — benefit from community and practitioner knowledge. If you know that the eligibility verification process works differently in practice than it is defined in the shared segment, your knowledge can improve the segment for everyone. This section explains how to contribute domain knowledge.</p>'),
  (v_group_id, 'Translating CivikStack for non-technical audiences', 'translating-civikstack-for-non-technical-audiences', 5, 'How to explain CivikStack to people who are not technologists.', '<h2 id="translating">Translating CivikStack for non-technical audiences</h2><p>CivikStack''s value is not in its technical architecture — it is in what that architecture reveals about whether civic services work. This section provides plain-language explanations, analogies, and talking points for explaining CivikStack to residents, community boards, elected officials, and other non-technical audiences.</p>');

  -- Group 5: For Practitioners in the Community
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'For Practitioners in the Community', 'for-practitioners-in-the-community', 5)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'The practitioner community identity', 'the-practitioner-community-identity', 1, 'What it means to be part of the practitioner community.', '<h2 id="practitioner-identity">The practitioner community identity</h2><p>The CivikStack practitioner community is composed of frontline workers, case managers, navigators, and social workers who identify as part of the ecosystem''s community of purpose. You are not just operators of a system — you are practitioners whose daily observations of how services work (and fail) are the foundation on which pathway truth is built.</p>'),
  (v_group_id, 'Why practitioner knowledge matters architecturally', 'why-practitioner-knowledge-matters-architecturally', 2, 'How practitioner observations are essential to system accuracy.', '<h2 id="practitioner-knowledge">Why practitioner knowledge matters architecturally</h2><p>The telemetry pipeline can measure what happens in a pathway. It cannot measure why. Practitioner knowledge fills the gap between measurement and understanding. When you observe that a step fails because the eligibility criteria were updated but the pathway was not, that observation is architecturally consequential — it identifies the root cause that telemetry alone cannot reveal.</p>'),
  (v_group_id, 'How your observations become structurally consequential', 'how-your-observations-become-structurally-consequential', 3, 'The pathway from observation to system correction.', '<h2 id="observations-consequential">How your observations become structurally consequential</h2><p>When you flag a pathway problem or submit a failure observation, it enters the governance process. If your observation reveals a systematic issue — not just a one-time exception — it can trigger a pathway governance review, a shared segment correction, or an RFC for a broader change. This section traces the path from your observation to structural correction.</p>'),
  (v_group_id, 'Connecting with other practitioners', 'connecting-with-other-practitioners', 4, 'How to find and connect with the practitioner community.', '<h2 id="connect-practitioners">Connecting with other practitioners</h2><p>The practitioner community connects through working group meetings, the practitioner newsletter, regional convenings, and the online practitioner forum. This section provides links to all practitioner community channels and the calendar of upcoming events.</p>');

  -- Group 6: Research and Journalism
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Research and Journalism', 'research-and-journalism', 6)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Using CivikStack data in research', 'using-civikstack-data-in-research', 1, 'Guidelines for using access reliability data in academic research.', '<h2 id="research-use">Using CivikStack data in research</h2><p>CivikStack access reliability data provides a continuous, step-level dataset about civic service pathway operations. Researchers can access anonymized data through formal data access agreements. This section explains the data architecture, available datasets, access procedures, and the methodological considerations for using access reliability data in research.</p>'),
  (v_group_id, 'The methodology documentation', 'the-methodology-documentation', 2, 'Technical documentation of the CivikStack measurement methodology.', '<h2 id="methodology">The methodology documentation</h2><p>The CivikStack measurement methodology is fully documented for peer review and replication. This section provides the complete methodology documentation including the DFR computation algorithm, the statistical validation procedures, the sampling methodology for geographic analysis, and the confidence interval calculations.</p>'),
  (v_group_id, 'Data access and use agreements', 'data-access-and-use-agreements', 3, 'How to obtain access to CivikStack data for research.', '<h2 id="data-access">Data access and use agreements</h2><p>Access to CivikStack data for research requires a formal data access agreement that specifies the research purpose, the data requested, the analysis plan, the publication plan, and the data security measures. The Foundation reviews data access requests and issues agreements for research that aligns with the ecosystem''s mission.</p>'),
  (v_group_id, 'Citation standards', 'citation-standards', 4, 'How to cite CivikStack data and methodology in academic work.', '<h2 id="citation-standards">Citation standards</h2><p>CivikStack provides standard citation formats for academic publications. Citations should reference the specific data version, the county deployment, the time period, and the DFR computation version. This section provides BibTeX templates, APA format examples, and guidance for citing methodology versus data.</p>'),
  (v_group_id, 'Journalist resources and embargoed data access', 'journalist-resources-and-embargoed-data-access', 5, 'Resources for journalists covering CivikStack findings.', '<h2 id="journalist-resources">Journalist resources and embargoed data access</h2><p>Journalists covering access reliability findings can request background briefings, data explanations, and embargoed access to forthcoming access reliability reports. The Foundation provides a media liaison, fact-checking support, and contextual background to help journalists accurately report on access reliability data.</p>'),
  (v_group_id, 'Contact for press inquiries', 'contact-for-press-inquiries', 6, 'How to reach the Foundation for press and media inquiries.', '<h2 id="press-contact">Contact for press inquiries</h2><p>For press inquiries about CivikStack, access reliability data, or the Foundation, contact the Foundation''s communications team. This section provides contact information, response time expectations, and guidance for different types of media inquiries.</p>');

  -- Group 7: The Foundation's Mission
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'The Foundation''s Mission', 'the-foundations-mission', 7)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'The founding commitment', 'the-founding-commitment', 1, 'The Foundation purpose and commitment.', '<h2 id="founding-commitment">The founding commitment</h2><p>The CivikStack Foundation was founded on a single commitment: that the gap between promised and actual civic services should not be invisible. Every design decision, every governance process, every architectural commitment in CivikStack flows from this founding commitment. The Foundation exists to maintain and protect this commitment for the communities that depend on it.</p>'),
  (v_group_id, 'The community we are building', 'the-community-we-are-building', 2, 'The vision for the CivikStack community.', '<h2 id="community-vision">The community we are building</h2><p>The CivikStack community is not a user base — it is a community of purpose. Counties, agencies, practitioners, developers, advocates, researchers, and residents are all participants in a shared commitment to making civic service access reliable, measurable, and accountable. This section describes the community we are building and the values that guide it.</p>'),
  (v_group_id, 'Events and convenings', 'events-and-convenings', 3, 'Upcoming CivikStack community events.', '<h2 id="events">Events and convenings</h2><p>The CivikStack community convenes through regular events: working group meetings, regional practitioner convenings, the annual CivikStack summit, and topical webinars. This section provides the event calendar, registration information, and archives of past events.</p>'),
  (v_group_id, 'The annual access reliability report', 'the-annual-access-reliability-report', 4, 'The Foundation ecosystem-wide annual report.', '<h2 id="annual-report">The annual access reliability report</h2><p>Each year, the Foundation publishes the Annual Access Reliability Report — an ecosystem-wide analysis of access reliability across all participating counties and verticals. The report identifies national trends, geographic patterns, and systemic issues. It is the most comprehensive picture of civic service access reliability available.</p>'),
  (v_group_id, 'How to stay connected', 'how-to-stay-connected', 5, 'Ways to stay informed about CivikStack developments.', '<h2 id="stay-connected">How to stay connected</h2><p>Stay connected with the CivikStack ecosystem through the community newsletter, the working group mailing lists, the practitioner forum, the developer community, and the Foundation''s public communications. This section provides signup links and descriptions of each communication channel.</p>');

END $$;
