/*
  # Seed Get Started sidebar groups and pages

  Creates 5 sidebar groups with ~30 child topic pages for the
  Get Started section. Organized by deployment role: counties,
  agencies, frontline workers, and compliance reporting.
*/

DO $$
DECLARE
  v_section_id uuid;
  v_group_id uuid;
BEGIN
  SELECT id INTO v_section_id FROM nav_sections WHERE slug = 'get-started';

  -- Group 1: Before You Begin
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Before You Begin', 'before-you-begin', 1)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Is CivikStack right for your situation', 'is-civikstack-right-for-your-situation', 1,
   'A decision framework for evaluating whether CivikStack fits your needs.',
   '<h2 id="right-for-you">Is CivikStack right for your situation</h2><p>CivikStack is designed for counties and agencies that deliver civic services to residents and want to measure whether those services actually work. If your organization operates service pathways — sequences of steps that residents follow to access housing, benefits, healthcare, workforce, or other civic services — CivikStack can measure whether those pathways are working as designed.</p><p>CivikStack is not a case management system, a benefits eligibility engine, or a program management tool. It is measurement infrastructure that sits alongside your existing systems and provides access reliability data that your existing systems cannot generate.</p>'),
  (v_group_id, 'What you will need', 'what-you-will-need', 2,
   'Technical and organizational prerequisites for deploying CivikStack.',
   '<h2 id="what-you-need">What you will need</h2><p>Deploying CivikStack requires three things: infrastructure capacity appropriate to your scale tier, staff capacity to configure and maintain the deployment, and organizational commitment to act on the access reliability data the system produces. The infrastructure requirements range from a single desktop for evaluation to a Kubernetes cluster for county production.</p>'),
  (v_group_id, 'The deployment decision checklist', 'the-deployment-decision-checklist', 3,
   'A structured checklist for making the deployment decision.',
   '<h2 id="decision-checklist">The deployment decision checklist</h2><p>Before deploying CivikStack, work through this checklist with your leadership team: Have you identified the service pathways you want to measure? Do you have the infrastructure capacity for your chosen scale tier? Do you have staff who can configure and maintain the deployment? Do you have organizational commitment to act on access reliability findings? Have you identified the compliance reporting requirements you want to automate?</p>');

  -- Group 2: For Counties — Deploying CivikGrid
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'For Counties — Deploying CivikGrid', 'for-counties-deploying-civikgrid', 2)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Choosing your scale tier', 'choosing-your-scale-tier', 1, 'How to select the right CivikGrid deployment tier.', '<h2 id="scale-tier">Choosing your scale tier</h2><p>CivikGrid offers five scale tiers. Tier 1 runs on a single desktop for evaluation and development. Tier 2 runs on a single server for small agencies. Tier 3 uses a small Kubernetes cluster for larger agencies. Tier 4 is the full county production deployment. Tier 5 supports multi-county federations and data center deployments. Choose based on the number of pathways you will measure and the number of concurrent users.</p>'),
  (v_group_id, 'Tier 1: Desktop and development', 'tier-1-desktop-and-development', 2, 'Single desktop deployment for evaluation.', '<h2 id="tier-1">Tier 1: Desktop and development</h2><p>Tier 1 runs the complete CivikStack architecture on a single desktop or laptop. It includes all seven RoutePack containers, a local telemetry pipeline, and a single vertical application. This tier is designed for evaluation, development, and training — not for production service delivery.</p>'),
  (v_group_id, 'Tier 2: Single server', 'tier-2-single-server', 3, 'Single server deployment for small agencies.', '<h2 id="tier-2">Tier 2: Single server</h2><p>Tier 2 runs CivikStack on a single server with Docker Compose. It supports a small number of concurrent users and a limited number of pathways. This tier is appropriate for a single agency operating one or two verticals with a small frontline staff.</p>'),
  (v_group_id, 'Tier 3: Small cluster', 'tier-3-small-cluster', 4, 'Small Kubernetes cluster for larger agencies.', '<h2 id="tier-3">Tier 3: Small cluster</h2><p>Tier 3 uses a small Kubernetes cluster (3-5 nodes) to provide redundancy and scaling. It supports multiple verticals, higher concurrency, and the full telemetry pipeline with Kafka. This tier is appropriate for a large agency or a small county with multiple participating agencies.</p>'),
  (v_group_id, 'Tier 4: County production', 'tier-4-county-production', 5, 'Full county production deployment.', '<h2 id="tier-4">Tier 4: County production</h2><p>Tier 4 is the full county production deployment with a properly sized Kubernetes cluster, high-availability infrastructure, full observability, and all verticals active. This tier supports county-wide deployment across multiple agencies with hundreds of frontline workers.</p>'),
  (v_group_id, 'Tier 5: Multi-county and data center', 'tier-5-multi-county-and-data-center', 6, 'Multi-county federation deployment.', '<h2 id="tier-5">Tier 5: Multi-county and data center</h2><p>Tier 5 supports multi-county federations with a shared data center deployment, cross-county federation, and connection to the Foundation ecosystem. This tier includes Delta Sharing for cross-county access reliability data sharing and the Foundation sync protocol.</p>'),
  (v_group_id, 'The deployment package', 'the-deployment-package', 7, 'What is included in the deployment package.', '<h2 id="deployment-package">The deployment package</h2><p>The CivikStack deployment package includes Helm charts for Kubernetes deployment, Docker Compose files for Tier 1-2, configuration templates, the conformance test suite, and documentation for each scale tier. The package is versioned and published through the Foundation''s release process.</p>'),
  (v_group_id, 'Step-by-step deployment', 'step-by-step-deployment', 8, 'Walkthrough of the deployment process.', '<h2 id="step-by-step">Step-by-step deployment</h2><p>This guide walks through the complete deployment process for your chosen tier: infrastructure provisioning, CivikGrid installation, initial configuration, vertical activation, telemetry validation, and federation connection. Each step includes verification checks to confirm correct operation before proceeding.</p>'),
  (v_group_id, 'Confirming correct operation', 'confirming-correct-operation', 9, 'How to verify your deployment is working correctly.', '<h2 id="confirm-operation">Confirming correct operation</h2><p>After deployment, run the CivikStack conformance test suite to verify that all components are operating correctly. The test suite validates telemetry flow, DFR computation, Privacy Envelope enforcement, lifecycle state transitions, and compliance report generation.</p>'),
  (v_group_id, 'Connecting to the Foundation ecosystem', 'connecting-to-the-foundation-ecosystem', 10, 'How to connect your deployment to the broader ecosystem.', '<h2 id="connect-foundation">Connecting to the Foundation ecosystem</h2><p>Connecting your CivikGrid deployment to the Foundation ecosystem enables shared segment synchronization, schema version updates, and participation in the cross-county access reliability data commons. This connection is optional but recommended for counties that want to benefit from community-governed pathway knowledge.</p>'),
  (v_group_id, 'Your first pathway', 'your-first-pathway', 11, 'Creating and publishing your first measured pathway.', '<h2 id="first-pathway">Your first pathway</h2><p>After deployment and connection, create your first pathway. This guide walks through pathway definition, step configuration, telemetry integration, Publish Gate validation, and the first DFR computation. By the end, you will have a live, measured pathway with real-time access reliability data.</p>');

  -- Group 3: For Agencies — Adopting a Vertical
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'For Agencies — Adopting a Vertical', 'for-agencies-adopting-a-vertical', 3)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Choosing your vertical', 'choosing-your-vertical', 1, 'How to select the right vertical for your agency.', '<h2 id="choose-vertical">Choosing your vertical</h2><p>Each of the ten CivikStack verticals is designed for a specific civic service domain. Choose the vertical that matches your agency''s primary service area. If your agency operates across multiple domains, you may adopt multiple verticals — each will generate its own access reliability data and compliance reports.</p>'),
  (v_group_id, 'What adoption requires from your agency', 'what-adoption-requires-from-your-agency', 2, 'Organizational requirements for vertical adoption.', '<h2 id="adoption-requires">What adoption requires from your agency</h2><p>Adopting a CivikStack vertical requires three commitments from your agency: configuring your service pathways in the vertical application, training your staff to record step outcomes, and establishing a governance process for reviewing access reliability findings and acting on pathway drift.</p>'),
  (v_group_id, 'Configuring your first pathway', 'configuring-your-first-pathway', 3, 'Step-by-step pathway configuration for agencies.', '<h2 id="first-pathway-config">Configuring your first pathway</h2><p>This guide walks through the pathway configuration process for agency administrators: mapping your existing service process to the pathway artifact structure, defining steps and expected outcomes, configuring failure codes relevant to your domain, and publishing the pathway through the Publish Gate.</p>'),
  (v_group_id, 'Training your staff', 'training-your-staff', 4, 'How to prepare frontline workers for CivikStack.', '<h2 id="training">Training your staff</h2><p>Training frontline workers to use a CivikStack vertical application focuses on two tasks: recording step outcomes as they deliver services, and using failure codes to classify why a step did not succeed. The training is designed to add minimal overhead to existing workflows while generating the telemetry that makes access reliability measurement possible.</p>'),
  (v_group_id, 'Connecting with partner agencies', 'connecting-with-partner-agencies', 5, 'Setting up interagency referral pathways.', '<h2 id="connect-partners">Connecting with partner agencies</h2><p>If your agency refers residents to other agencies, or receives referrals from other agencies, CivikStack can measure the reliability of those referral pathways. This guide walks through configuring cross-vertical referral connections with your partner agencies.</p>');

  -- Group 4: For Frontline Workers
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'For Frontline Workers', 'for-frontline-workers', 4)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'What is new in your workflow', 'what-is-new-in-your-workflow', 1, 'What changes for frontline workers using CivikStack.', '<h2 id="whats-new">What is new in your workflow</h2><p>CivikStack adds one thing to your workflow: recording the outcome of each step as you deliver services. When you complete an intake assessment, you record whether it succeeded. When a document collection step fails, you record the failure and select the appropriate failure code. This is the telemetry that makes pathway measurement possible.</p>'),
  (v_group_id, 'What stays the same', 'what-stays-the-same', 2, 'What does not change in your daily work.', '<h2 id="stays-same">What stays the same</h2><p>Your professional judgment, your relationship with the people you serve, your decision-making process, and the services you deliver — all of these stay the same. CivikStack measures the pathway, not the worker. It measures whether the system is working, not whether you are performing.</p>'),
  (v_group_id, 'Recording step outcomes', 'recording-step-outcomes', 3, 'How to record step outcomes in your vertical application.', '<h2 id="recording-outcomes">Recording step outcomes</h2><p>Each step in your workflow has an outcome: success, failure, or timeout. Recording the outcome is typically a single action — selecting the result from a dropdown or clicking a button. The application handles the rest: generating the telemetry event, attaching the correct pathway version, and sending it through the Privacy Envelope to the measurement pipeline.</p>'),
  (v_group_id, 'Using failure codes', 'using-failure-codes', 4, 'How to classify why a step did not succeed.', '<h2 id="failure-codes">Using failure codes</h2><p>When a step fails, you select a failure code that describes why. Failure codes are standardized within each vertical — they describe common failure modes like "documentation not available," "eligibility criteria not met," "appointment not kept," or "service capacity exceeded." These codes are what allows CivikStack to identify systemic problems rather than individual cases.</p>'),
  (v_group_id, 'When to flag a pathway problem', 'when-to-flag-a-pathway-problem', 5, 'How to report when the pathway itself seems wrong.', '<h2 id="flag-problem">When to flag a pathway problem</h2><p>Sometimes the problem is not that a step failed — the problem is that the pathway itself does not match reality. The steps are in the wrong order, a required step is missing, or the pathway assumes a resource that no longer exists. When you observe this, flag it as a pathway problem. Your observation becomes part of the governance review process that keeps pathways aligned with reality.</p>'),
  (v_group_id, 'Getting help', 'getting-help', 6, 'Where to go when you need support.', '<h2 id="getting-help">Getting help</h2><p>If you encounter problems with your vertical application, contact your agency''s CivikStack administrator. If the problem is with the pathway itself — it does not match how the service actually works — use the pathway problem flag to report it. For technical issues, your county''s CivikGrid administrator can escalate to the Foundation support community.</p>');

  -- Group 5: Compliance Reporting
  INSERT INTO sidebar_groups (section_id, title, slug, sort_order)
  VALUES (v_section_id, 'Compliance Reporting — Getting Your First Report', 'compliance-reporting-getting-your-first-report', 5)
  RETURNING id INTO v_group_id;

  INSERT INTO section_pages (group_id, title, slug, sort_order, description, content) VALUES
  (v_group_id, 'Housing — HUD CoC and HMIS', 'housing-hud-coc-and-hmis', 1, 'Generating HUD compliance reports from housing telemetry.', '<h2 id="housing-compliance">Housing — HUD CoC and HMIS</h2><p>The Housing vertical generates compliance outputs aligned to HUD Continuum of Care and HMIS requirements. This guide walks through generating your first housing compliance report: selecting the reporting period, reviewing the telemetry-derived metrics, validating against your HMIS data, and exporting in the required format.</p>'),
  (v_group_id, 'Benefits — CMS Medicaid and SNAP', 'benefits-cms-medicaid-and-snap', 2, 'Generating CMS compliance reports from benefits telemetry.', '<h2 id="benefits-compliance">Benefits — CMS Medicaid and SNAP</h2><p>The Public Benefits vertical generates compliance outputs aligned to CMS Medicaid and SNAP reporting requirements. Telemetry-derived metrics include enrollment processing times, eligibility determination accuracy, and benefit issuance timelines — all computed from the step-level telemetry stream.</p>'),
  (v_group_id, 'Workforce — WIOA title I', 'workforce-wioa-title-i', 3, 'Generating WIOA compliance reports from workforce telemetry.', '<h2 id="workforce-compliance">Workforce — WIOA title I</h2><p>The Workforce vertical generates compliance outputs aligned to WIOA Title I requirements. Metrics include participant enrollment, service delivery events, credential attainment, and employment outcomes — all derived from the telemetry pipeline rather than manual reporting.</p>'),
  (v_group_id, 'Reentry — Second Chance Act', 'reentry-second-chance-act', 4, 'Generating Second Chance Act compliance reports.', '<h2 id="reentry-compliance">Reentry — Second Chance Act</h2><p>The Reentry vertical generates compliance outputs aligned to Second Chance Act reporting requirements. Telemetry captures reentry service pathway events including housing placement, employment assistance, treatment engagement, and supervision compliance — providing a continuous record of service delivery.</p>'),
  (v_group_id, 'Behavioral Health — CCBHC and 988', 'behavioral-health-ccbhc-and-988', 5, 'Generating behavioral health compliance reports.', '<h2 id="bh-compliance">Behavioral Health — CCBHC and 988</h2><p>The Behavioral Health vertical generates compliance outputs aligned to CCBHC and 988 crisis line reporting requirements. Metrics include initial contact response times, follow-up engagement rates, treatment pathway completion, and crisis resolution outcomes.</p>'),
  (v_group_id, 'Coverage — CMS managed care', 'coverage-cms-managed-care', 6, 'Generating managed care compliance reports.', '<h2 id="coverage-compliance">Coverage — CMS managed care</h2><p>The Healthcare Coverage vertical generates compliance outputs aligned to CMS managed care requirements. Telemetry captures enrollment processing, plan assignment, primary care connection, and care coordination events — providing the data needed for managed care performance reporting.</p>'),
  (v_group_id, 'Student Support — McKinney-Vento and IDEA', 'student-support-mckinney-vento-and-idea', 7, 'Generating student support compliance reports.', '<h2 id="student-compliance">Student Support — McKinney-Vento and IDEA</h2><p>The Student Support vertical generates compliance outputs aligned to McKinney-Vento homeless student provisions and IDEA special education requirements. Metrics include identification timelines, service connection events, educational stability measures, and accommodation delivery tracking.</p>'),
  (v_group_id, 'Legal Aid — LSC performance', 'legal-aid-lsc-performance', 8, 'Generating LSC performance compliance reports.', '<h2 id="legal-compliance">Legal Aid — LSC performance</h2><p>The Civil Legal Aid vertical generates compliance outputs aligned to LSC performance reporting requirements. Telemetry captures case intake, service delivery events, outcome tracking, and client access measures — providing the quantitative foundation for LSC performance reporting.</p>');

END $$;
